CC = g++
EXE = 0810917_lab3.cpp

all:$(OBJ)
	$(CC) -I /uhome/chome/2022EDA/2022EDA036/lab3/cudd-3.0.0/cudd -I /uhome/chome/2022EDA/2022EDA036/lab3/cudd-3.0.0/util -I /uhome/chome/2022EDA/2022EDA036/lab3/cudd-3.0.0 $(EXE) /uhome/chome/2022EDA/2022EDA036/lab3/cudd-3.0.0/cudd/.libs/libcudd.a -lm -O3 -o Lab3

clean:
	rm -f $(EXE) 